FROM python:3.7

# set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

WORKDIR /app

# copy requirement file before rest of directory for caching
COPY ./requirements.txt /app/

RUN pip install -r requirements.txt

COPY . /app